### ISSUE TITLE
[BUG] Project Versioning

### ISSUE THREAD

**Issue by amcgreevy-r7** [opensearch-project/opensearch-go#115]
**What is the bug?**
The project does not follow the Go versioning requirements of a /v2 being added to the package in the go mod file when the first major version bump occurs. Because of this the client is not usable as adding it to the go.mod file as a dependency results in a failed build due to the version not existing, or being an invalid version because the package doesn't contain a /v2 at the end. Even adding the +incompatible does not seem to fix it.

**How can one reproduce the bug?**
Create a project and add this project as a dependency
run go mod tidy

**What is the expected behavior?**
Go dependency management will fail to find the project and fail the build

**What is your host/environment?**
 - OS: Darwin
 - Version Latest
 - Plugins

**Do you have any screenshots?**
no but can get some if needed adding exact wording of error message.
`server response: not found: github.com/opensearch-project/opensearch-go@v2.0.0+incompatible: invalid version: module contains a go.mod file, so module path must match major version ("github.com/opensearch-project/opensearch-go/v2")`

**Do you have any additional context?**
no

**Comment by VachaShah** [comment]
@amcgreevy-r7 Thank you for raising this issue!

v2 is available now. I tried:

**go.mod**
```
module my-go-app

require github.com/opensearch-project/opensearch-go/v2 v2.0.0

go 1.15
```

**main.go**
```
package main

  import (
    "log"

    "github.com/opensearch-project/opensearch-go/v2"
  )

  func main() {
    os, _ := opensearch.NewDefaultClient()
    log.Println(opensearch.Version)
    log.Println(os.Info())
  }
```

**Output**
```
> go run main.go 
go: downloading github.com/opensearch-project/opensearch-go/v2 v2.0.0
go: extracting github.com/opensearch-project/opensearch-go/v2 v2.0.0
go: finding github.com/opensearch-project/opensearch-go/v2 v2.0.0
2022/06/16 18:03:50 2.0.0
2022/06/16 18:03:50 [0 <nil>] EOF
```

Can you please confirm?
