### ISSUE TITLE
[FEATURE] Add support for AWS Sigv4 request signer

### ISSUE THREAD

**Issue by VachaShah** [opensearch-project/opensearch-go#117]
Add support for signed requests via AWS sigv4.

**Comment by VijayanB** [comment]
Aws sigv4 is already supported https://github.com/opensearch-project/opensearch-go/blob/main/signer/aws/aws.go.

**Comment by matelang** [comment]
Also, I've created a PR for using AWS Sigv4 with AWS SDK V2 in case you are searching for that. Hopefully it gets approved, but until then you can just put the signer in your codebase.

https://github.com/opensearch-project/opensearch-go/pull/116

**Comment by VachaShah** [comment]
> @VachaShah Aws sigv4 is already supported https://github.com/opensearch-project/opensearch-go/blob/main/signer/aws/aws.go. Do we need something more than this?

@VijayanB Thanks for pointing it out! I created this as part of a meta issue for clients. Will make sure to mark this as done.

**Comment by VachaShah** [comment]
> Also, I've created a PR for using AWS Sigv4 with AWS SDK V2 in case you are searching for that. Hopefully it gets approved, but until then you can just put the signer in your codebase.
> 
> #116

@matelang Thank you very much for adding this!

**Comment by VachaShah** [comment]
Support for AWS Sigv4 is added.
