### ISSUE TITLE
[BUG] UpdateRequest never update.

### ISSUE THREAD

**Issue by htanhx** [opensearch-project/opensearch-go#132]
**What is the bug?**
the api.update.go using wrong HTTP request path.

**How can one reproduce the bug?**
Steps to reproduce the behavior: create UpdateRequest and execute it.

**What is the expected behavior?**
Swap line 101 & 103 of "opensearchapi/api.update.go".

**What is your host/environment?**
 - OS: macos
 - Version 12
 - Plugins

**Do you have any screenshots?**
None.

**Do you have any additional context?**
None

**Comment by bjornskold** [comment]
This also affects api.create.go. Generated path /{index}/{type}/{id}/_create is no longer accepted by opensearch 2.0
