### ISSUE TITLE
Not able to import signer/awsv2

### ISSUE THREAD

**Issue by 17Ants** [opensearch-project/opensearch-go#141]
Hello, I am using the  v2 version of the client but not able to go get 
 github.com/opensearch-project/opensearch-go/v2/signer/awsv2

I am however able to get 
github.com/opensearch-project/opensearch-go/v2/signer/
github.com/opensearch-project/opensearch-go/v2/

And also able to use the v1 version of the signer. Any help will be appreciated as we want to avoid using sessions based on aws go sdk v1 .

Thanks in Advance.

**Comment by dblock** [comment]
I think this was added in https://github.com/opensearch-project/opensearch-go/pull/116, we simply didn't release it (yet). I opened https://github.com/opensearch-project/opensearch-go/issues/143. Try the code on main in the meantime?

**Comment by VachaShah** [comment]
Version 2.1.0 is now released with AWS SDK V2 signer support

https://github.com/opensearch-project/opensearch-go/releases/tag/v2.1.0
https://pkg.go.dev/github.com/opensearch-project/opensearch-go/v2@v2.1.0
