### ISSUE TITLE
Release 2.1.0

### ISSUE THREAD

**Issue by dblock** [opensearch-project/opensearch-go#143]
### Is your feature request related to a problem?
People are [trying](https://github.com/opensearch-project/opensearch-go/issues/141) to use some meaty functionality added in https://github.com/opensearch-project/opensearch-go/pull/116.  

### What solution would you like?
1. Bump the version to 2.1.0 since we've added features per semver.
2. Release 2.1.0.

**Comment by 5imonGustafsson** [comment]
Any updates on this? I am waiting to be able to use aws v2 signer with this lib.

**Comment by VachaShah** [comment]
Version 2.1.0 is now released with AWS SDK V2 signer support 

https://github.com/opensearch-project/opensearch-go/releases/tag/v2.1.0
https://pkg.go.dev/github.com/opensearch-project/opensearch-go/v2@v2.1.0
