### ISSUE TITLE
[FEATURE] Automate and document the release process

### ISSUE THREAD

**Issue by dblock** [opensearch-project/opensearch-go#144]
### Is your feature request related to a problem?
Enable any maintainer to do a release by clicking a button.

### What solution would you like?
Automation and documentation similar to https://github.com/opensearch-project/opensearch-java/blob/main/RELEASING.md#releasing.
 
### Do you have any additional context?
Coming from #143. We want to release new features (more) often.

**Comment by wbeckler** [comment]
If once you create a tag you can see the release in the Go package manager, doesn't this already exist?

**Comment by VachaShah** [comment]
Closing this since the documentation is added.
