### ISSUE TITLE
[BUG] `BulkIndexer` holds onto memory

### ISSUE THREAD

**Issue by jcass8695** [opensearch-project/opensearch-go#148]
### What is the bug?
Observed when using the `BulkIndexer` and during a period of heavy indexing, an application's memory usage will climb to some high level and remain there after the period of indexing has completed, suggesting that there are allocated objects that are not being/not able to be GCed.

### How can one reproduce the bug?
Still working on being able to reproduce this locally.

### What is the expected behavior?
After a period of indexing, the memory usage returns to it's pre-indexing level.

### What is your host/environment?
Application is deployed in a Docker container as an ECS task.

### Do you have any screenshots?
![Memory % Utilization (Min, Avg, Max) (2)](https://user-images.githubusercontent.com/10819039/185975124-697ce9fd-2630-4afd-8160-edeeaee7c2bb.png)
![CPU % Utilization (Min, Avg, Max) (1)](https://user-images.githubusercontent.com/10819039/185975323-af8795ee-e350-4625-904f-4122daee73dd.png)

As you can see in the above screenshots, memory usage & CPU usage of the application container align during a period of heavy indexing. When the CPU usage subsides, the memory usage remains at its elevated level. The return to a lower level corresponds with the container being recycled.

### Do you have any additional context?
* Library version: `github.com/opensearch-project/opensearch-go v1.1.0`

**Comment by wbeckler** [comment]
This is a good catch. Feel free to take a crack at it if you have any thoughts on where the issue lies.

**Comment by dblock** [comment]
This issue seems to say that we expect CPU/memory to stay stable (low) when doing more work (indexing). Isn't that proportional to the work being done?

**Comment by wbeckler** [comment]
@dblock The issue is not that CPU or memory spikes during indexing, it's that memory wasn't reclaimed starting at 15:30 in the graphs, when CPU went back down. The indexing was finished but memory stayed high until the container recycled.

**Comment by jcass8695** [comment]
Hey guys, we did some further investigation on this and we are pretty confident that it's not a memory leak. We believe that the memory is not in use, but the Go garbage collector is not deallocating it. I believe this is an optimisation whereby if there is no memory pressure on the system, the GC will not free memory that is not immediately needed, bit of context on that [in this comment](https://github.com/golang/go/issues/41444#issuecomment-720165157) on the Go Github repo.

I'll close out the issue.
