### ISSUE TITLE
Source (_source) input parameter has confusing type

### ISSUE THREAD

**Issue by tmewett** [opensearch-project/opensearch-go#158]
The _source input parameter is encoded in the API as type `[]string`.

This is consistent with API docs like [update document](https://opensearch.org/docs/latest/opensearch/rest-api/document-apis/update-document/) which have it as type List - but not with their description which has "Default is true" and implies it is a Boolean.

In the end I had to specify true as `[]string{"true"}`, which doesn't seem very ergonomic. Not to mention that it's unclear what would happen if I had a field called "true".

Thank you 🙇‍♂️

related https://github.com/opensearch-project/documentation-website/issues/1237

**Comment by wbeckler** [comment]
Both of you feel free to collaborate and work on this. Also, please identify whether this will break any working code that relies on the old setup. If so, we would want to merge this into the 3.x line.

**Comment by zethuman** [comment]
Can we close this issue by merge [#285 ]

**Comment by dblock** [comment]
Yep, closing.
