### ISSUE TITLE
[FEATURE] Can we not have the latest version support both opensearch 1.x and 2.x

### ISSUE THREAD

**Issue by mannukalra** [opensearch-project/opensearch-go#169]
Planning to use the API for telegraf output plugin since there are workaround based solutions available for elasticsearch output plugin.
Plugin should support both opensearch 1.x and 2.x.
I'm new to golang, please suggest if there is an alternative available.

**Comment by mannukalra** [comment]
Can help if you could provide little some guidance.

**Comment by dblock** [comment]
@VachaShah do you have a good PR example that added integration tests to a client recently that @mannukalra can get inspired by?

**Comment by tannerjones4075** [comment]
Should this issue be closed?

**Comment by dblock** [comment]
Yep, support matrix is up-to-date.
