### ISSUE TITLE
[BUG] license problem with https://github.com/opensearch-project/opensearch-go/blob/main/internal/build/go.sum

### ISSUE THREAD

**Issue by nlacey** [opensearch-project/opensearch-go#201]
https://github.com/opensearch-project/opensearch-go/blob/main/internal/build/go.sum
Depends on github.com/kr/logfmt v0.0.0-20140226030751-b84e30acd515/go.mod

This old hash doesn't provide any kind of license.
You can see by looking at $GOCODE/pkg/mod/github.com/kr/logfmt@v0.0.0-20140226030751-b84e30acd515

You, or whatever sub-dependency bring in that package, needs to updates to the current github.com/kr/logfmt, so you can pick up the current MIT license for that repo

Thanks

**Comment by dblock** [comment]
I found https://github.com/kr/logfmt/pull/7. Care to help us update this project @nlacey ?

**Comment by nlacey** [comment]
@dblock as far as I can tell.
If you just cd $GOCODE/src/github.com/opensearch-project/opensearch-go/internal/build
and just update all dependences
go get -u
go mod tidy
you should no longer see any reference to kr/logfmt  in you go.sum file which would resolve this license issue

**Comment by dblock** [comment]
That's something we need to commit here, right? Please PR?

**Comment by nlacey** [comment]
created https://github.com/opensearch-project/opensearch-go/pull/205 for you

**Comment by nlacey** [comment]
resolved with https://github.com/opensearch-project/opensearch-go/pull/205
