### ISSUE TITLE
[BUG] Unclear how to get a detailed error

### ISSUE THREAD

**Issue by dblock** [opensearch-project/opensearch-go#220]
### What is the bug?

Go noob here. Following USER_GUIDE to implement a basic demo in https://github.com/dblock/opensearch-go-client-demo. How do I get the detailed error from the client?

```
$ go run main.go 
2023/01/23 11:21:29 indices.create: cannot retrieve information from OpenSearch
exit status 1
```

**Comment by Jakob3xD** [comment]
I am not a maintainer but maybe this helps you.
```
func main() {
	resp, err := client.Indices.Create(index_name, client.Indices.Create.WithWaitForActiveShards("1"))
	if err != nil {
		log.Fatal("indices.create: ", err)
	}
	defer resp.Body.Close() // Avoid Memory leak
	if resp.IsError() { // Check the StatusCode
		return OpensearchRespError(resp)
	}
	log.Print(resp)
}

func OpensearchRespError(resp *opensearchapi.Response) error {
	body, err := io.ReadAll(resp.Body) // Read the Reponse Body
	if err != nil {
		return err
	}
	return fmt.Errorf("status: %v, msg: %s", resp.StatusCode, string(body)) // Return the StatusCode + Message/Body as Error
}
```
https://github.com/opensearch-project/opensearch-go/blob/v2.2.0/opensearchapi/opensearchapi.response.go#L100-L102

**Comment by dblock** [comment]
I didn't realize I was supposed to _also_ check `resp.IsError()` (!).

Am I doing it right https://github.com/dblock/opensearch-go-client-demo/commit/5698c5530a12835a536bf325eefad06e41141207?

Is there really no way to avoid all this error checking boilerplate?

**Comment by Jakob3xD** [comment]
In your first 4 change lines you return resp. For the others you return `err` what should be nil, so you would need to log `resp` instead. Moreover it would make sens to do this in functions to avoid code duplication.

Personally I prefer creating the requests and executing it in an extra function that handles the errors.
I have a function that looks like this:
```
func main {
	req := &opensearchapi.IndicesCreateRequest{
		Index:               index_name,
		WaitForActiveShards: "1",
	}
	if err := OpensearchDo(ctx, osClient, req); err != nil {
		fmt.Sprintf("%s", err)
		os.Exit(1)
	}

}
func OpensearchDo(ctx context.Context, osClient *opensearch.Client, req opensearchapi.Request) error {
	resp, err := req.Do(ctx, osClient)
	if err != nil {
		return err
	}
	defer resp.Body.Close()
	if resp.IsError() {
		body, err := io.ReadAll(resp.Body)
		if err != nil {
			return err
		}
		return fmt.Errorf("status: %v, msg: %s", resp.StatusCode, string(body))
	}
	return nil
}
``` 

Maybe it would make sens to add a `Error()` function to `resp` which return the error type being nil if not an error or containing an error with the Opensearch response.

```
func (r *Response) Error() error {
	if r.StatusCode > 299 {
		body, err := io.ReadAll(r.Body)
		if err != nil {
			return err
		}
		return fmt.Errorf("status: %v, msg: %s", resp.StatusCode, string(body))
	}
	return nil
}
```

**Comment by dblock** [comment]
I used some of this in https://github.com/dblock/opensearch-go-client-demo/commit/98481fb36b51cacc59ef95d0677821f0e3cc3b5f. If you think there's something that can be improved there, would love a PR into my demo project, please and thank you! For example, I am not deferring `resp.Body.Close()`, but that seems like something one needs to do? I couldn't come up with something clean where it auto-closes (I need the body of the response from search).

I think we need a way to transform the JSON errors returned from OpenSearch in the library to error types. For example when I get back `{"error":{"root_cause":[{"type":"resource_already_exists_exception","reason":"index [movies/90OPJgInTdqYuE-LGLeoRA] already exists","index":"movies","index_uuid":"90OPJgInTdqYuE-LGLeoRA"}],"type":"resource_already_exists_exception","reason":"index [movies/90OPJgInTdqYuE-LGLeoRA] already exists","index":"movies","index_uuid":"90OPJgInTdqYuE-LGLeoRA"}` I'd like to just write `err.type` and `err.reason`, this way one can check for things like `resource_already_exists_exception`. We can even go further and specialize errors such as `resource_already_exists_exception` into `ResourceAlreadyExistsError`. WDYT? Interested in contributing to this library?

**Comment by Jakob3xD** [comment]
With this PR you could load the error into the `*opensearch.Error` struct using `errors.As` and check for the Type and Reason.
Maybe some fields needs to be added to the Error struck but for now the basic function should work.

Moreover it makes the IsError function obsolete as you can just check if the error return from the Err() func is nil.

**Comment by dblock** [comment]
Should we close this with #246? @Jakob3xD
