### ISSUE TITLE
[Testing Confirmation] Confirm current testing requirements

### ISSUE THREAD

**Issue by scrawfor99** [opensearch-project/opensearch-go#238]
As part of the discussion around implementing an organization-wide testing policy, I am visiting each repo to see what tests they currently perform. I am conducting this work on GitHub so that it is easy to reference. 

Looking at the OpenSearch Go repository, it appears there is 

| Repository  | Unit Tests | Integration Tests | Backwards Compatibility Tests | Additional Tests | Link | 
| ------------- | ------------- | ------------- | ------------- | ------------- | ------------- | 
| OpenSearch Go | <li>- [x] </li> | <li>- [x] </li> | <li>- [ ] </li> | License Headers, Changelog Verifier, Link Checker, Lint Checker | https://github.com/opensearch-project/opensearch-go/issues/238 | 

I don't see any requirements for code coverage in the testing documentation. If there are any specific requirements could you respond to this issue to let me know? 

If there are any tests I missed or anything you think all repositories in OpenSearch should have for testing please respond to this issue with details.

**Comment by wbeckler** [comment]
Backwards compatibility testing config is here: https://github.com/opensearch-project/opensearch-go/blob/main/.github/workflows/test-compatibility.yml

**Comment by scrawfor99** [comment]
Hi @wbeckler thank you for taking your time to reply. I will correct this note.
