### ISSUE TITLE
[FEATURE] Add a code/markdown linter

### ISSUE THREAD

**Issue by dblock** [opensearch-project/opensearch-go#260]
### Is your feature request related to a problem?

Add a linter that formats code, markdown, etc.

### What solution would you like?

- A linter that auto-formats code.
- CI that fails if the linter didn't run and offers how to run it.

**Comment by zethuman** [comment]
@dblock can we close this issue?

**Comment by dblock** [comment]
Yes, done in #261, thanks! 

Btw, you can say "Closes #261" in a PR and it will auto-close the issue when the PR is merged.
