### ISSUE TITLE
[FEATURE] Release 3.0

### ISSUE THREAD

**Issue by dblock** [opensearch-project/opensearch-go#264]
### Is your feature request related to a problem?

We have some awesome (and breaking) changes in 3.0 that help developers write better code, e.g. https://github.com/opensearch-project/opensearch-go/pull/246#issuecomment-1479384967.

### What solution would you like?

Release 3.0!

**Comment by wbeckler** [comment]
There's a possible [issue](https://github.com/opensearch-project/opensearch-go/issues/283) coming down the pipe that might be breaking. It would be nice to pile all the breaking stuff into one release so we don't need to go to 4.0.

**Comment by Jakob3xD** [comment]
@dblock Imo we could do a release once the two open PRs get merged.
I don´t think that we will have the plugins like security and ism ready withing the next few weeks and as they should only extend and not brake anything, I see no point in holding back a release.

**Comment by dblock** [comment]
💯

**Comment by dblock** [comment]
@Jakob3xD I think we're good to go, are we? Want to make a release?

**Comment by Jakob3xD** [comment]
> @Jakob3xD I think we're good to go, are we? Want to make a release?

What is the exact process to do a new release?
Do I make a PR where I bump the version in `internal/version/version.go` to 3.0.0 and change the CHANGELOG.md from `## [Unreleased]` to `## [v3.0.0]`, then merge it into main? Or don´t we keep a history of CHANGELOG and only list unreleased changes? Afterwards create branches named `3.x` and `3.0`. So that I create a tag named `v3.0.0` out of branch `3.0`.

**Comment by dblock** [comment]
@Xtansia Did you do the last one?

I believe yes, 1) you make changes on main for the version and CHANGELOG, then make a tag and the rest is automated, 2) increment version to 3.0.1 and PR/commit that.

I don't think we need a 3.x or a 3.0 branch, we can continue releasing off main. Those are only needed if we want to continue releasing 2.x versions for example, which I'd rather not.

Will you help us with documenting this as you go in https://github.com/opensearch-project/opensearch-go/blob/main/RELEASING.md, please?

**Comment by Xtansia** [comment]
I didn't do the last release, Vacha did, I don't have maintainer permissions on this client.

The version bump PR from then shows a couple places to change the version: https://github.com/opensearch-project/opensearch-go/commit/288e46ef4856890304c70208c2a8bd38d88a166e

**Comment by Jakob3xD** [comment]
I created the Tag and mad a release https://github.com/opensearch-project/opensearch-go/releases/tag/v3.0.0 I hope this is okay? Please edit if something is wrong.

**Comment by dblock** [comment]
Looking at https://pkg.go.dev/github.com/opensearch-project/opensearch-go/ I don't see a release. I have no idea what the "right way" is, @VachaShah could you help make a release and help us make sure that's automated and documented correctly this time around?

**Comment by Jakob3xD** [comment]
It is now present https://pkg.go.dev/github.com/opensearch-project/opensearch-go/v3

**Comment by dblock** [comment]
Amazing. I upgraded my little demo project in https://github.com/dblock/opensearch-go-client-demo/commit/bad06d1ee59e3560951f01228e3894777084bfc8. Do PR any improvements to the code ;)

**Comment by dblock** [comment]
Reopening this since we still need to bump the version to 3.0.1. 

How does the magic of publishing a release for the go client happen? Is it something we registered once on [pkg.go.dev](http://pkg.go.dev/) and it just auto-publishes all releases from GitHub? @VachaShah

**Comment by VachaShah** [comment]
Apologies for being late on this! I was out on vacation. For golang packages, pushing a tag to the repo makes them available to use. https://go.dev/doc/modules/publishing

**Comment by Jakob3xD** [comment]
> Reopening this since we still need to bump the version to 3.0.1. @Jakob3xD

Why do we need this? What change is happening with the release?

**Comment by dblock** [comment]
@Jakob3xD I suggest we bump the version for the _next_ developer iteration, so that we don't have code that still says 3.0 while it already has changes on top of that (it's no longer 3.0). We also need to update CHANGELOG to Unreleased. I did this in https://github.com/opensearch-project/opensearch-go/pull/448, take a look?
