### ISSUE TITLE
[Guide] Search

### ISSUE THREAD

**Issue by nhtruong** [opensearch-project/opensearch-go#277]
Create `guides/search.md` similar to the [Ruby guide](https://github.com/opensearch-project/opensearch-ruby/blob/main/guides/search.md)

You must assure that: 
- All code-blocks, when run from start to finish in order they appear in the guide, do not throw any errors. If you want to demonstrate that certain statements will throw errors, they must be wrapped in a `try/catch` and print out the expected error.
- All code-blocks are properly marked with the language it's written in (i.e.  ` ```ruby `)
- The instructions, though mostly identical to the Ruby guide, are suitable for this repo.

**Comment by dblock** [comment]
https://github.com/opensearch-project/opensearch-go/pull/291
