### ISSUE TITLE
[FEATURE] Add tests for Document API

### ISSUE THREAD

**Issue by zethuman** [opensearch-project/opensearch-go#280]
### Is your feature request related to a problem?
I was always worried about projects where there are no full-fledged tests, at least I didn't see tests in the document CRUD API)

### What solution would you like?
Write at least integration tests for document CRUD API

### Do you have any additional context?
Always open to contribute and write tests

**Comment by wbeckler** [comment]
Go for it!

**Comment by Jakob3xD** [comment]
With https://github.com/opensearch-project/opensearch-go/pull/421 all opensearchapi functions now have integration tests. Only the optional parameters of the requests are not directly tested. Might want to open a new issue for that.
