### ISSUE TITLE
[BUG] UpdateRequest does not work properly

### ISSUE THREAD

**Issue by zethuman** [opensearch-project/opensearch-go#282]
### What is the bug?
Now, I am writing test cases to the document APIs #280, and found that UpdateRequest does not update document by script. 

### How can one reproduce the bug?
To reproduce bug, create index, create document with body  

`{ "title": "Tenet", "director": "Christopher Nolan", "year": "2019" }`

```
r: opensearchapi.UpdateByQueryRequest{
  Index: []string{index},
  Body:  strings.NewReader(`{ "query": { "term": { "title": "Tenet" } }, "script" : { "source": "ctx._source.title += params.title", "lang": "painless", "params" : { "title" : "TeneT" } } }`),
}
```
I got this:

```
Not equal: 
expected: map[string]interface {}{"batches":0, "deleted":0, "failures":[]interface {}{}, "noops":0, "requests_per_second":-1, "retries":map[string]interface {}{"bulk":0, "search":0}, "throttled_millis":0, "throttled_until_millis":0, "timed_out":false, "took":4, "total":0, "updated":1, "version_conflicts":0}
actual  : map[string]interface {}{"batches":0, "deleted":0, "failures":[]interface {}{}, "noops":0, "requests_per_second":-1, "retries":map[string]interface {}{"bulk":0, "search":0}, "throttled_millis":0, "throttled_until_millis":0, "timed_out":false, "took":4, "total":0, "updated":0, "version_conflicts":0}
        	            	
```

### What is the expected behavior?
Expected updated document and count of updated documents in response

### What is your host/environment?
MacOS Ventura 

### Do you have any screenshots?
<img width="973" alt="image" src="https://user-images.githubusercontent.com/51375666/230145022-746077b7-167d-4255-b39b-72588b0fa9d9.png">

**Comment by wbeckler** [comment]
you might need to wait for back-to-back requests.

**Comment by zethuman** [comment]
What is it mean? How to reproduce this?

**Comment by wbeckler** [comment]
I mean, you might need to sleep(10) or something like that, so that the server can finish indexing the document. Back-to-back requests will fail.

**Comment by zethuman** [comment]
I tried to sleep 10, 20 seconds, but document is not updated...

**Comment by zethuman** [comment]
@wbeckler yes, the problem was in indexing. That is, after adding, you need to update the indexing and then do the manipulations. To test this functionality added a test case
