### ISSUE TITLE
[BUG] Windows compatibility with Makefile

### ISSUE THREAD

**Issue by Tokesh** [opensearch-project/opensearch-go#308]
I'm just begginer in Open Source development and my English in process, so sorry if i'm bit confusing you with easy questions 
### What is the bug?
'Developer Guide' working on my MacOS. But i want to install opensearch as well on my computer with Windows.
'Make' commands in Terminal doesn't work on Windows like by default on Mac. You can solve it by MinGW(installing and adding to PATH environment of PC). Here discussion [about it ](https://stackoverflow.com/questions/23723364/windows-7-make-is-not-recognized-as-an-internal-or-external-command-operabl) on StackOverflow
But if you run in Terminal such commands 'make cluster.build' or 'mingw32-make cluster.build' that anyway doesnt working(error in screenshots)
Currently i'm just taking commands from Makefile and running by myself and that's working

### How can one reproduce the bug?
'Make' on Windows not working like on Linux platforms. You should have some predefined compiler like MinGW.
You can write 'Mingw32-make'(depends which file from Mingw you add to PATH environment) its similar to 'Make'.
And when you write 'mingw32-make cluster.build cluster.start' that happen

### What is the expected behavior?
Created docker container of project

### What is your host/environment?
Windows 10
Docker version 20.10.23

### Do you have any screenshots?
![image](https://user-images.githubusercontent.com/78027392/232858605-3c5d22c5-fd5d-45bf-9742-43089a838c76.png)

### Do you have any additional context?
So if you give me direction of solving of this problem, i can do it!
Probably we should give some more guidelines for Windows users

**Comment by dblock** [comment]
Appreciate any contributions in documenting/fixing issues of how to develop on Windows, but keep in mind that usually that's pretty different/heavy. Maybe there's a shorter path with WSL2?

**Comment by Tokesh** [comment]
> Appreciate any contributions in documenting/fixing issues of how to develop on Windows, but keep in mind that usually that's pretty different/heavy. Maybe there's a shorter path with WSL2?

Perfect! I just fixed it by WSL 2. But that was a bit hard. If you want, i can write some specific short guideline how to install WSL2 and use makefile with WSL. 
I followed the steps from the Microsoft site, but on several links, for some reason they have a lot of irrelevant information.
Or I can add some tips for future Windows developers in the Developer Guide(to use WSL2 and how to use WSL, without installation).
I hope the product will grow, sooner or later the question will arise
Links of Microsoft pages:
https://learn.microsoft.com/en-us/windows/wsl/install
https://learn.microsoft.com/en-us/windows/wsl/install-manual

**Comment by dblock** [comment]
> Or I can add some small tips for future Windows developers in the Developer Guide(to use WSL2 and how to use WSL, without installation). About 1-2 sentences ~

I think this is the right answer. Go for it! Think of the next person who will want for it to "just work on Windows" and write enough that ... "it just works on Windows" :)

**Comment by Tokesh** [comment]
Hello @dblock ! I hope you are doing well.
Thank you for looking at all my pull requests and merging it. 
I didn't update changelog, i think that small update. Do i need to update changelog or that's fine?
This is my first issue and pull request at OpenSearch project. I am incredibly glad that I am in such an environment!

**Comment by dblock** [comment]
It's fine, no need to update CHANGELOG for small stuff like .md's

**Comment by Tokesh** [comment]
May I close this issue? I think everything fine with compatibility now
I can reference PR which was merged.

**Comment by dblock** [comment]
Closing via https://github.com/opensearch-project/opensearch-go/pull/309.
