### ISSUE TITLE
[BUG] undefined: opensearchapi.Error

### ISSUE THREAD

**Issue by r3v4s** [opensearch-project/opensearch-go#339]
### What is the bug?
undefined: opensearchapi.Error

### How can one reproduce the bug?
1. follow main branch [user guide](https://github.com/opensearch-project/opensearch-go/blob/main/USER_GUIDE.md)

### What is the expected behavior?
no error..?

### What is your host/environment?
macOS 13.4.1
go 1.20

### Do you have any screenshots?
![image](https://github.com/opensearch-project/opensearch-go/assets/104744707/dee43e17-adc5-4ebc-87d3-5e5412091304)

![image](https://github.com/opensearch-project/opensearch-go/assets/104744707/2381f0e8-25dc-4ea0-bf4d-5506f99b5110)

### Do you have any additional context?
no

**Comment by Jakob3xD** [comment]
The `opensearchapi.Error` is only available in the main branch and was not released yet.
The latest release is v2.3.0 and you can find the [user guide in the v2.3.0 tag](https://github.com/opensearch-project/opensearch-go/blob/v2.3.0/USER_GUIDE.md).

**Comment by r3v4s** [comment]
> The `opensearchapi.Error` is only available in the main branch and was not released yet. The latest release is v2.3.0 and you can find the [user guide in the v2.3.0 tag](https://github.com/opensearch-project/opensearch-go/blob/v2.3.0/USER_GUIDE.md).

aha, understood.
