### ISSUE TITLE
mapper [x] cannot be changed from type [float64] to [long]

### ISSUE THREAD

**Issue by 0x0elliot** [opensearch-project/opensearch-go#357]
i feel like this might be a problem in the go library.

this is an oddly specific example, and please correct me if i am wrong but, for a value:

```
x := float64(205)
```

and then, when x is used further in any opensearch variables, it causes the error i gave above. to make a fix, i had to do something like this:

```
x = x + 0.1
```

i feel like something like this should be handled out of the box in this client because fixes like these might not be sustainable because of their nature. what do you think? am i wrong to begin with to assume what i did?

**Comment by dblock** [comment]
Do you think you can turn this into a (failing) unit test?

**Comment by 0x0elliot** [comment]
yeah sure. want me to try shooting a PR?

**Comment by dblock** [comment]
@0x0elliot I really don't know where to fix this, I am just hand-waving! Maybe @Jakob3xD has some pointers? :)

**Comment by Jakob3xD** [comment]
I am not even sure where this error occurs. Maybe @0x0elliot can follow the Bug Issue template to add more information.
As of right now I assume this is an issue when parsing responses from Opensearch and trying to update something on opensearch with the parsed value?
