### ISSUE TITLE
mapper [x] cannot be changed from type [float] to [long]

### ISSUE THREAD

**Issue by 0x0elliot** [opensearch-project/opensearch-go#386]
The following covers what the bug is, instructions to reproduce it and why i think it happens.

- We use opensearch where I work
- One day, I got this error:
<img width="819" alt="Screenshot 2023-10-08 at 4 32 06 AM" src="https://github.com/opensearch-project/opensearch-go/assets/60684641/a8951321-b88e-4f76-a524-d775db6f406c">
- I am confident this is because of how the library deals with types internally to speak to opensearch API. the following is why:
- This error comes specifically when workflow.actions.position.X has a value of **float64(206)**. Usually, since these positions are entered by the user through the GUI, the probability of these positional values being perfect is less. Usually, they have a decimal at the end. But when i got this bug, It just so happened that there was a perfect value at use.
<img width="362" alt="Screenshot 2023-10-08 at 4 37 09 AM" src="https://github.com/opensearch-project/opensearch-go/assets/60684641/400ff53b-b43b-4608-a46c-b96314503774">

- Here is how the struct for this object looks like:
<img width="329" alt="Screenshot 2023-10-08 at 4 39 37 AM" src="https://github.com/opensearch-project/opensearch-go/assets/60684641/5c1e67d4-4588-468b-97c1-a810efed98b7">

Here is what i think is happening demonstrated with an example (this is pretty interesting):
![image](https://github.com/opensearch-project/opensearch-go/assets/60684641/6d264faa-3010-4afe-8cdf-2290f672add6)
- this is for a golang code that uses a float value, puts it into a struct (which expects float64), converts it into JSON.

![image](https://github.com/opensearch-project/opensearch-go/assets/60684641/cc81195e-1c1c-45a2-9b6b-f3404818b2a9)
![image](https://github.com/opensearch-project/opensearch-go/assets/60684641/959ed2e7-7a7e-4661-afe2-6c3bbd59fb9b)
- Notice how even for values which are typed as float64, the JSON object converted might convert them into what might be confused as an integer, rather than a float.
- This might cause the API server to throw the errors it is throwing :)

### Update:
<img width="619" alt="Screenshot 2023-10-08 at 5 09 07 AM" src="https://github.com/opensearch-project/opensearch-go/assets/60684641/436cc716-cc5a-428d-a21f-37ab9d2019f3">

this fixes the issue temporarily but i can see similar annoying bugs with timestamps as well. Thought you all should know.

**Comment by 0x0elliot** [comment]
For context, we do use json.Marshal() ourselves. hmm. Technically, it's us who is causing this bug, but I wonder if you folks can also watch out for something like this somehow.

**Comment by dblock** [comment]
Thanks for the report @0x0elliot. What do you expect the library to do in this case? Maybe try to write a unite test that reproduces the error?

**Comment by 0x0elliot** [comment]
> Thanks for the report @0x0elliot. What do you expect the library to do in this case? Maybe try to write a unite test that reproduces the error?

Thanks for the response @dblock. I decided that it's rather a `encoding/json` issue and has nothing to do with go-opensearch.
