### ISSUE TITLE
[FEATURE] Make raw JSON REST requests to OpenSearch 

### ISSUE THREAD

**Issue by dblock** [opensearch-project/opensearch-go#395]
### Is your feature request related to a problem?

Coming from https://github.com/opensearch-project/opensearch-clients/issues/62, add support for making raw JSON requests.

### What solution would you like?

Add a high level DSL, e.g. `client.get` and `client.post`.

### Do you have any additional context?

Some of this may already be implemented under https://github.com/opensearch-project/opensearch-go/issues/331. At the very least we need documentation that doesn't use any high level DSL methods.

**Comment by Jakob3xD** [comment]
This can already be done by using the Perform function of the client. https://github.com/opensearch-project/opensearch-go/blob/f4a8446cdf24b7f79dc9989070603585a83baaed/opensearch.go#L265

You just need to build/ create the http request by your self.

**Comment by dblock** [comment]
@Jakob3xD thanks, we just need to document this and provide a working sample ;)
