### ISSUE TITLE
[BUG] Error using scroll mode query

### ISSUE THREAD

**Issue by wunengweili** [opensearch-project/opensearch-go#422]
### What is the bug?
When using ScrollRequest to request, the opensearch server will report: too_long_http_line_exception; An HTTP line is larger than 4096 bytes

### Cause
When the client requests, the parameters are placed directly on the URL, but the length of scroll_id is very long. If the opensearch server does not have special configuration, an error will be reported

### Personal local solution
Place the request parameters in the request body and comment out the request parameters on the url

**Comment by Jakob3xD** [comment]
The fix is now merged in main.
