### ISSUE TITLE
[BUG]Clusters deployed using IPV6 do not support the DiscoverNodes method.

### ISSUE THREAD

**Issue by Zhang-jie-jun** [opensearch-project/opensearch-go#458]
### What is the bug?
When using the opensearch-go library to access an opensearch cluster deployed with IPV6, an access error will occur when calling other APIs after calling the DiscoverNodes method.

### How can one reproduce the bug?
+ Construct a client using NewClient
+ Call client.DiscoverNodes method
+ Calling another API
For example: opensearchapi.CatMasterRequest{}.Do(context.Background(), client)

### What is the expected behavior?
Able to use the opensearch-go library to normally access the OpenSearch cluster deployed with IPV6

### What is your host/environment?
go1.17.1 Windows/amd64

### Do you have any screenshots?
![image](https://github.com/opensearch-project/opensearch-go/assets/82801500/e03bc9ee-8e3f-4eff-80ea-3eaca67e7da1)

### Do you have any additional context?
+ Failure
![image](https://github.com/opensearch-project/opensearch-go/assets/82801500/a0a01b33-b474-478c-8829-2432b256ad01)

+Success
![image](https://github.com/opensearch-project/opensearch-go/assets/82801500/1ea9fef0-8887-465d-9fc4-49c11ddce742)

**Comment by dblock** [comment]
Looks legit. Want to try to add a test and implement a fix for this?
