### ISSUE TITLE
[BUG] The Search API (in Version 3.0.0) is not working without setting an Index

### ISSUE THREAD

**Issue by dom192** [opensearch-project/opensearch-go#470]
### What is the bug?
It  seems, that it is not possible to call the Search function of Client:
```go
// Search executes a /_search request with the optional SearchReq
func (c Client) Search(ctx context.Context, req *SearchReq) (*SearchResp, error)
``` 
without setting `Indices` in the `SearchReq`.
			
### How can one reproduce the bug?
Call the Search function without specifying Indices 
```go
	content := strings.NewReader(
	`	{
		"query": {
		  "match_all": {}
		}
	  }`)

	resp, err := client.Search(
		ctx,
		&opensearchapi.SearchReq{
			Indices: []string{},
			Body:    content,
		},
	)
``` 

### What is the expected behavior?
The expected result should be no error and a valid opensearch result, but instead I get an error:
`error msg: failed to json unmarshal body: invalid character '<' looking for beginning of value`
 The root cause of the problem is getting a http status code 400 Bad Request with http body:
`"<html>\r\n<head><title>400 Bad Request</title></head>\r\n<body>\r\n<center><h1>400 Bad Request</h1></center>\r\n<hr><center>nginx</center>\r\n</body>\r\n</html>\r\n"`
Which is not handled right. The code tries to ` json.Unmarshal` the html and generates the misleading error message.

### What is your host/environment?
Ubuntu 22.04.3 LTS
API version 3 (github.com/opensearch-project/opensearch-go/v3/opensearchapi)

### Do you have any screenshots?
no

### Do you have any additional context?
I debugged the issue and found the root cause I think. The problem is the `GetRequest` function:
![image](https://github.com/opensearch-project/opensearch-go/assets/23055909/dfca5e0d-21af-42ab-bd93-4ab490874329)
In case of no Indices is set, path is set to _search
```go
path = "_search"
``` 
this causes the Bad Request response. To fix this I appended a "/" to _search:
```go
path = "/_search"
``` 
after that the everything worked like expected :)

**Comment by Jakob3xD** [comment]
Tanks for reporting this issue.
Yes, the path should be prefixed with `/ `.

Can you please tell what you client looks like? Are you using AWS Signing or something like that, as I can not reproduce it with our integration tests and I want to adjust them so it does not happen again.

**Comment by dom192** [comment]
> Tanks for reporting this issue. Yes, the path should be prefixed with `/ `.
> 
> Can you please tell what you client looks like? Are you using AWS Signing or something like that, as I can not reproduce it with our integration tests and I want to adjust them so it does not happen again.

Thanks for the fast response. I tried it out in a local test setup:
local Kubernetes clusters with kind using basic auth
```go
	return v3api.NewClient(
		v3api.Config{
			Client: osV3.Config{
				Username:  config.OS_USER,
				Password:  config.OS_PASSWORD,
				Addresses: []string{config.OS_URL},

				Transport: &http.Transport{
					TLSClientConfig: &tls.Config{InsecureSkipVerify: true},
				},
			},
		})
```

**Comment by Jakob3xD** [comment]
Hm, weird. I can't seem to reproduce the issue with the integration test. I did the same requests and tried to modify the client address but it does not affect it. If I understand the URL lib correctly it should not matter if the leading slash is missing. I tried looking into this for a few hours but I don't want to dig through the net/http lib to much.

It there any chance you can find where this issue is exactly coming from so we can test it as I am not able to reproduce it.

**Comment by dom192** [comment]
The error happens on the server side. are you testing against a real endpoint? When the "/" is missing the server responds with 400.

**Comment by Jakob3xD** [comment]
> The error happens on the server side. are you testing against a real endpoint? When the "/" is missing the server responds with statuscode 400.

I am testing against a real opensearch container. Running `make cluster.build cluster.start` and `make test-integ`.
It looks like you have a nginx in between your setup. Can you see how the requests looks like when it reaches the nginx by looking at the nginx logs?

I am still not getting where exactly the missing `/` is causing the 400 as it is present in the URL when sending the requests. If it was missing the request would not work at all as `your-opensearch.com_search` is not a valid domain.

**Comment by dom192** [comment]
You are probably right with the nginx, but I have no access to it to see the logs. Will ask for access and come back to you soon.

**Comment by wbeckler** [comment]
Maybe you can get the requests using the Logger functionality in the client?

**Comment by dom192** [comment]
Thanks for the hint with the logger within the client. I tried it out and this is my result.
Result without my fix (path = "_search"):
```shell
2024-03-12T09:55:37Z POST https://myurl/_search [status:400 request:183ms] 
< <html>
< <head><title>400 Bad Request</title></head>
< <body>
< <center><h1>400 Bad Request</h1></center>
< <hr><center>nginx</center>
< </body>
< </html>
``` 
Result with my fix (path = "/_search"):
```shell
2024-03-12T09:50:32Z POST https://myurl/_search [status:200 request:1.082s]
< {"took":45,"timed_out":false,"_shards":{"total":659,"successful":659,"skipped":658,"failed":0},"hits":{"total":{"value":0,"relation":"eq"},"max_score":null,"hits":[]}}
``` 
The strange thing is, that the POST call printed out by the logger looks equal!

**Comment by dom192** [comment]
Hi again,
today a checked with a colleague who has more rights than me ;)
We figured out , that a direct access to the opensearch service with port 9200 works fine in both ways. In the case with a NGINX Ingress between it is only working with path = "/_search". I found also in other opensearch api function that there is a leading "/".  Would be great if you could fix that :)

**Comment by dblock** [comment]
@dom192 want to try to make a fix yourself? start by writing a unit test that shows the problem?
