### ISSUE TITLE
Accept either ELASTICSEARCH_URL or OPENSEARCH_URL

### ISSUE THREAD

**Issue by VijayanB** [opensearch-project/opensearch-go#49]
To support backward compatibility, if addresses are not specified in config during new client api, we will look for addresses either  from ELASTICSEARCH_URL or OPENSEARCH_URL environment variable. if we find both, then will exit with error message that both can't be set .

**Comment by jmazanec15** [comment]
@VijayanB Given that it is the OpenSearch Go client, would it make sense to give OPENSEARCH_URL environment variable priority over ELASTICSEARCH_URL?

**Comment by VijayanB** [comment]
@jmazanec15 do you mean, taking OPENSEARCH_URL over ELASTICSEARCH_URL if both are defined?

**Comment by jmazanec15** [comment]
@VijayanB Yes
