### ISSUE TITLE
Handle application/vnd.elasticsearch+json;compatible-with=7

### ISSUE THREAD

**Issue by VijayanB** [opensearch-project/opensearch-go#53]
Handle application/vnd.elasticserach+json;compatible-with=7 in backward compatible way

**Comment by rushiagr** [comment]
Looks like this feature was added in ES version 7.13. See PHP client docs: https://www.elastic.co/guide/en/elasticsearch/client/php-api/current/http-meta-data.html#_send_the_api_compatibility_layer and Python client release documentation: https://github.com/elastic/elasticsearch-py/releases/tag/v7.13.0 . Also, features seems to be present to upgrade from  ES v7 to v8, whereas the same doesn't apply to OpenSearch. So my question is, do we really need this in OpenSearch?

**Comment by wbeckler** [comment]
For the same reason mentioned [here](https://github.com/opensearch-project/opensearch-py/issues/46), this should be closed as not applicable to the OpenSearch product.
