### ISSUE TITLE
Cleanup unused branches

### ISSUE THREAD

**Issue by dblock** [opensearch-project/opensearch-go#547]
Coming from https://github.com/opensearch-project/opensearch-clients/issues/64, cleanup unused branches.

For some unused branches we probably want to save state, so maybe note the last revision of any branch being deleted in this issue as it's being closed.

**Comment by VachaShah** [comment]
Deleted 3 branches related to backport and dependabot. All other branches in this repo are related to releases. Will keep them as is.
