### ISSUE TITLE
[BUG]Unable to install because of checksum error

### ISSUE THREAD

**Issue by tvaughan73** [opensearch-project/opensearch-go#548]
### What is the bug?
_A clear and concise description of the bug._

Getting an error because of a checksum error in the jsondiff package.  
It was reported here: https://github.com/wI2L/jsondiff/issues/21

Can we get this package bumped up to [v0.5.2](https://github.com/wI2L/jsondiff/releases/tag/v0.5.2)

### How can one reproduce the bug?
_Steps to reproduce the behavior._

### What is the expected behavior?
_A clear and concise description of what you expected to happen._

### What is your host/environment?
_Operating system, version._
Windows 11
### Do you have any screenshots?
_If applicable, add screenshots to help explain your problem._
![image](https://github.com/opensearch-project/opensearch-go/assets/850122/c7d22b6b-0ad5-4a75-9bf1-0609c75fa281)

### Do you have any additional context?
_Add any other context about the problem._

**Comment by dblock** [comment]
@tvaughan73 This is odd. Does it only happen on Windows? 

Yes on updating, care to help? Want to PR a change?

**Comment by tvaughan73** [comment]
Looks like this was already changed in the main branch.  Will just need to wait for it to be released.

**Comment by dblock** [comment]
Open an issue for "Release v. Next" if this is blocking you?
