### ISSUE TITLE
[BUG] MappingFieldResp struct is not parsed correctly.

### ISSUE THREAD

**Issue by agnivade** [opensearch-project/opensearch-go#560]
### What is the bug?
MappingFieldResp struct is not parsed correctly.

### How can one reproduce the bug?

A short snippet

```go
mappingFieldResp, err := client.Indices.Mapping.Field(ctx, &opensearchapi.MappingFieldReq{
		Fields:  []string{"type"},
		Indices: []string{indexName},
	})
	fmt.Println("---------------------")
	io.Copy(os.Stderr, mappingFieldResp.Inspect().Response.Body)
	fmt.Printf("\n%+v\n", mappingFieldResp.Indices)
	fmt.Printf("\n---------------------\n")
```

prints 

```
---------------------
{"channels":{"mappings":{"type":{"full_name":"type","mapping":{"type":{"type":"keyword"}}}}}}
map[]
---------------------
```

### What is the expected behavior?
It should parse the data correctly

### What is your host/environment?
Linux

### Do you have any additional context?
The issue is that there is an additional `Indices` field which is there inside the struct which is not allowing the response to be parsed properly.

Here: https://github.com/opensearch-project/opensearch-go/blob/6836d76494fa993ba7874b2f1762993a5ffaf40f/opensearchapi/api_indices-mapping.go#L63, we need to pass `data.Indices` instead of `data`.

I am not sure how the unit tests are passing. But it seems like a pretty straightforward bug to me.

EDIT: Something like this works:
```go

var mappingFieldResp map[string]struct {
  Mappings json.RawMessage `json:"mappings"`
}
httpResp, err := es.client.Client.Do(ctx, &opensearchapi.MappingFieldReq{
  Fields:  []string{"type"},
  Indices: []string{indexName},
}, &mappingFieldResp)
```

**Comment by dblock** [comment]
Looks like a miss. Want to fix it here?

Also note that we would like to generate the client from spec to catch all this kind of problems (#284), so would be great to check the [spec](https://github.com/opensearch-project/opensearch-api-specification) for correctness for this API.

**Comment by agnivade** [comment]
I can, but currently I have a workaround so it's not urgent for me. I'll see if I can find some time.
