### ISSUE TITLE
[BUG] ISM Allocation action does not match Opensearch server expectation

### ISSUE THREAD

**Issue by kellen-miller** [opensearch-project/opensearch-go#591]
### What is the bug?

I'm attempting to unmarshal a json file containing an ISM policy into the [ism.Policy](https://github.com/opensearch-project/opensearch-go/blob/main/plugins/ism/api_policies.go#L62) struct. The documentation for the [allocation action](https://opensearch.org/docs/latest/im-plugin/ism/policies/#allocation) specifies that the `require` value be of type string. This is also the type that the [go struct's](https://github.com/opensearch-project/opensearch-go/blob/main/plugins/ism/api_policies.go#L229) `require` value is.

However in the example in the docs, it shows that the value really should be an object.
```json
    "allocation": {
      "require": { "temp": "warm" }
    }
```
and this is also what is expected by the Opensearch server. 

If I encode the json as a string, i.e. `"{ \"temp\": \"warm\" }"`, I can then marshal it into the go struct, but the server will then throw a parsing error saying that it expects an Object, not a String.

A similar thing happens with the [wait_for](https://github.com/opensearch-project/opensearch-go/blob/main/plugins/ism/api_policies.go#L232) field. The docs and go struct specify it needs to be a string, but the server expects a bool.

### How can one reproduce the bug?
Attempt to json marshal the below json into an [ism.Policy](https://github.com/opensearch-project/opensearch-go/blob/main/plugins/ism/api_policies.go#L62) struct.

**policyContent**
```json
{
    "policy": {
        "description": "hot warm workflow",
        "default_state": "hot",
        "schema_version": 1,
        "states": [
            {
                "name": "hot",
                "actions": [
                    {
                        "rollover": {
                            "min_index_age": "1d",
                            "min_size": "1gb"
                        }
                    }
                ],
                "transitions": [
                    {
                        "state_name": "warm",
                        "conditions": {
                            "min_rollover_age": "1m"
                        }
                    }
                ]
            },
            {
                "name": "warm",
                "actions": [
                    {
                        "allocation": {
                            "require": {
                                "temp": "warm"
                            },
                            "wait_for": false
                        }
                    }
                ]
            }
        ],
        "ism_template": [
            {
                "index_patterns": [
                    "myindex*"
                ],
                "priority": 100
            }
        ]
    }
}
```

### What is the expected behavior?
The above json is what the opensearch server expects. If you directly send the above json to the server like so, it will succeed.
```go
        // create ism client, open policy json file above and load policyContents
        
	req, err := opensearch.BuildRequest(http.MethodPut,
		"/_plugins/_ism/policies/myindex_policy",
		strings.NewReader(policyContents),
		nil, nil)
	if err != nil {
		return fmt.Errorf("failed to create ISM policy request for myindex: %w", err)
	}

	resp, err := ismClient.Client.Perform(req)
	if err != nil {
		return fmt.Errorf("failed to create ISM policy for myindex: %w", err)
	}
	if resp.StatusCode == http.StatusCreated {
		return nil
	}
```

I think the documentation needs to be updated to say that it accepts an object, which would allow the go struct value to be a type of `map[string]string` or `json.RawMessage` or whatever is deemed fit.

### What is your host/environment?
_Operating system, version._

### Do you have any screenshots?
_If applicable, add screenshots to help explain your problem._

### Do you have any additional context?
_Add any other context about the problem._

**Comment by dblock** [comment]
[Catch All Triage - [1](https://github.com/dblock), [2](https://github.com/krisfreedain), [3](https://github.com/amistrn)]

There's an effort to generate some of this from spec @kellen-miller, see #284. Would be helpful if you want to ensure these APIs are present and properly documented in the spec itself?
