### ISSUE TITLE
[RELEASE] v4.3.0

### ISSUE THREAD

**Issue by kellen-miller** [opensearch-project/opensearch-go#628]
Issue to ask for release `v4.3.0` to be created. 

https://github.com/opensearch-project/opensearch-go/pull/627#issuecomment-2393851459

cc @dblock

**Comment by kellen-miller** [comment]
Hey just wanted to follow up on this, see if there was any timeline for it.

**Comment by dblock** [comment]
Released, https://pkg.go.dev/github.com/opensearch-project/opensearch-go/v4@v4.3.0
