### ISSUE TITLE
[FEATURE] Support version and routing fields in bulk indexer

### ISSUE THREAD

**Issue by nevins-b** [opensearch-project/opensearch-go#68]
**Is your feature request related to a problem?**
Currently the bulk index request structs do not support the version or routing options. 

**What solution would you like?**
Let's add these fields to the structs and update the writer to build the json correctly.

**What alternatives have you considered?**
I'm not sure there are any, with how the current implementation of the bulk indexer works we're unable to set these fields unless they are available on the structs.

**Do you have any additional context?**
https://opensearch.org/docs/opensearch/rest-api/document-apis/index-document/ the `version`, `routing`, and `version_type` fields are the ones requested

**Comment by VijayanB** [comment]
@nevins-b Thanks for feature request. We will review and get back to you soon.

**Comment by VijayanB** [comment]
Looks like more meta fields can be added. What do you think about creating a new structure with all meta fields and deserialize using json api.

**Comment by nevins-b** [comment]
We could definitely do that, though we'd either end up copying field values around or break the current object structure I think

**Comment by efanfast** [comment]
+1 for the feature request; our team is using AWS opensearch as our search index; 
we are expecting this feature so that we can use the doc timestamp as the `external version` to solve the overwritings between offline batch and real-time indexing.

**Comment by efanfast** [comment]
> Looks like more meta fields can be added. What do you think about creating a new structure with all meta fields and serialize using json api.

it's better to add more fields in BulkIndexerItem; that way, we can reuse the BulkIndexer.add() interface directly
