### ISSUE TITLE
[BUG] Tag version with "v" prefix to make it work with go.mod

### ISSUE THREAD

**Issue by henvic** [opensearch-project/opensearch-go#73]
Hi, go mod requires tags to start with a "v" prefix. Otherwise, it's invalid.
I've noticed this when trying to update a go.mod to use the latest release.

Could you please retag it to be `v1.0.0`?

Context:
https://github.com/golang/go/issues/30146#issuecomment-492669348
https://github.com/golang/go/issues/32945

**Comment by henvic** [comment]
Sounds good to me.

**Comment by kynrai** [comment]
This would be the best solution for golang users
