### ISSUE TITLE
[FEATURE] Types for ISM in opensearchapi

### ISSUE THREAD

**Issue by dbason** [opensearch-project/opensearch-go#74]
**Is your feature request related to a problem?**
Currently there's no support for the ISM APIs in opensearchapi.  This means to use that feature you need to manually extend the API yourself

**What solution would you like?**
It would be nice if this was included.

**What alternatives have you considered?**
Currently we have written our own implementation.

**Comment by wbeckler** [comment]
@dbason at the moment nobody is working on this. If you have a working implementation, would you be willing to share it as a PR? There is an open question of where to put the plugin methods and how to name them. I think it would be useful to see a working implementation.

**Comment by saketjain01** [comment]
Hello Everyone,

Curious to know if there is any further information available on support of this feature in opensearchapi-go. Or any pointers to the alternatives available to implement ISM policy for data streams in golang.

Appreciate any help here.

**Comment by salamer** [comment]
any progress?

**Comment by dblock** [comment]
@salamer AFAIK nobody is working on this, please feel free to pick it up
