### ISSUE TITLE
[FEATURE] Add IAM authentication option

### ISSUE THREAD

**Issue by aetter** [opensearch-project/opensearch-go#75]
If people want to connect to an Amazon OpenSearch Service cluster, they have to figure out how to use this client alongside some third-party signing library and/or the AWS SDK, which is non-trivial due to how we (by design) conceal the underlying HTTP requests that the client makes. We should offer IAM signing as an option, just like the OpenSearch CLI does.

**Is your feature request related to a problem?**
If you want to use this client with an Amazon OpenSearch Service cluster that has IAM authentication rather than basic authentication, good luck.

**What solution would you like?**

When initializing the client, an AuthType option. If basic (or null), accept username and password. If IAM, accept options for access key, secret key, session token, region, and service.

**What alternatives have you considered?**

An additional Go IAM signing library for use on top of the client. But given that it would only work with the client, it seems better and easier to just add it to the client.

**Do you have any additional context?**

https://github.com/opensearch-project/OpenSearch/issues/1400

**Comment by pieisgood** [comment]
It could be easier and faster to add an option for using the aws SDK Signer/v4 , allow the config to take in a signer and just sign the request at request time, could even have a default signer that fulfills the interface? Since the v4 signing credential method is the method currently used in the AWS OpenSearch connection tutorial currently

**Comment by goynam** [comment]
Hey @VijayanB ,

As discussed, we need a way to pass in HTTP client while creating the os client so that we can send signed aws requests . 
Similar thing is done in ES client : https://github.com/olivere/elastic/blob/release-branch.v7/client.go

**Comment by goynam** [comment]
Hi @hyandell , @VijayanB 

Planning to add support for IAM signing using aws v4 signer library by allowing contruction of http transport object which actually performs http requests . similar to what is mentioned here : 

https://github.com/jriquelme/awsgosigv4/blob/master/elasticexample_test.go

Please let me know if i can proceed with this change and raise a pull request.

**Comment by VijayanB** [comment]
@goynam Thanks for looking into this issue. Please go ahead and create pull request, we will review it. Thanks

**Comment by rmasclef** [comment]
Hi ! Sorry to comment on a closed Issue 😬

May I suggest adding an example of `Authentication through IAMs` in the README ?

I don't know if a lot of people uses `identity-based-policies` on AWS Opensearch Service, but for those like me who does, it has been very hard to figure out how to get the opensearch-sdk to use IAMs to connect and perform requests 👍

---

For those who walk through this PR here is an example of how to perform authentication through IAMs

```go
package main

import (
	"context"
	"io"
	"log"

	"github.com/aws/aws-sdk-go/aws/session"
	"github.com/opensearch-project/opensearch-go"
	"github.com/opensearch-project/opensearch-go/opensearchapi"
	requestsigner "github.com/opensearch-project/opensearch-go/signer/aws"
)

const domainEndpoint = "https://vpc-test-opensearch-with-iams-lpzna7o3rotzh7rgc6nsbchomm.eu-west-1.es.amazonaws.com/"

func main() {
	ctx := context.Background()

	signer, err := requestsigner.NewSigner(session.Options{SharedConfigState: session.SharedConfigEnable})
	if err != nil {
		log.Fatal(err)
	}

	clientConfig := opensearch.Config{
		Addresses: []string{domainEndpoint},
		Signer: signer,
	}

	client, err := opensearch.NewClient(clientConfig)
	if err != nil {
		log.Fatal("client creation err", err)
	}

	ping := opensearchapi.PingRequest{}

	resp, err := ping.Do(ctx, client)
	if err != nil {
		log.Fatal(err)
	}
	defer resp.Body.Close()

	if resp.IsError() {
		log.Println("ping resp code", resp.StatusCode)

		respBody, err := io.ReadAll(resp.Body)
		if err != nil {
			log.Fatal("response body read err", err)
		}

		log.Println(respBody)

		return
	}

	log.Println("PING OK")
}
```

I hope it helps !

**Comment by VijayanB** [comment]
@rmasclef Thanks for suggestion. Looks good. Are you willing to contribute it to README.md since you already have a working example?

**Comment by rmasclef** [comment]
@VijayanB I'd be honoured 😉 

As the README.md looks more like a glossary maybe you'd prefer for the example to be somewhere else ?

**Comment by VijayanB** [comment]
Thanks for pointing it out. Lets add it here: https://github.com/opensearch-project/opensearch-go/blob/main/USER_GUIDE.md for now. Will copy this example in case we needed this on docs.

**Comment by rmasclef** [comment]
Here you go -> https://github.com/opensearch-project/opensearch-go/pull/93
