### ISSUE TITLE
[PROPOSAL] Use with golang Elastic Search equivalent

### ISSUE THREAD

**Issue by gedw99** [opensearch-project/opensearch-go#82]
** What kind of business use case are you trying to solve? What are your requirements?

Need golang server to have more control over our destiny and hate the JVM ( sorry )

**What is the problem? What is preventing you from meeting the requirements?**

We are golang coders in the team and so using a golang server is much easier.

**What are you proposing? What do you suggest we do to solve the problem or improve the existing situation?**

THIS: https://github.com/prabhatsharma/zinc

Its taking off. Does not have clustering yet
but there is another clustered one here https://github.com/mosuka/phalanx, but it needs the ziny APi on top of it.

**What are your assumptions or prerequisites?**

Dont think i am assuming much. but i probably dont know what i dont know.

**What are remaining open questions?**

i would like to know if this interests the community.  
I can put time into it, but it would be nice to know if others like this idea and is they also want to get involved.

**Comment by dblock** [comment]
If Zinc has a 100% compatible API with ES/OpenSearch, then this client should "just work". Have you tried it?

**Comment by gedw99** [comment]
I plan to work on it .

zinc does not yet provide all of the API but it’s does cover done of it .

**Comment by gedw99** [comment]
Cc

@prabhatsharma

**Comment by wbeckler** [comment]
Given @mosuka's intention to create a different kind of database without all of the methods of opensearch, I propose we close this Issue.
