### ISSUE TITLE
Release v1.1.0

### ISSUE THREAD

**Issue by VijayanB** [opensearch-project/opensearch-go#91]
Second minor release

- [x] Create 1.1 branch
- [x] Generate release notes
- [x] Create release tag

**Comment by rm-hull** [comment]
Any indication when this might be published?
[#81 is a much needed feature for this release]

**Comment by VijayanB** [comment]
@rm-hull Will try to get to this before end of this week. Thanks.

**Comment by VijayanB** [comment]
https://github.com/opensearch-project/opensearch-go/releases/tag/v1.1.0
